#! /usr/bin/env bash

echo "== Delete bucket"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name to delete"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME \
--region us-east-1
