#! /usr/bin/env bash

echo "List objects"

if [ -z "$1" ]; then
    echo "Bucket name is required to list its objects"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects \
--bucket $BUCKET_NAME \
--query Contents[].Key