#! /usr/bin/env bash

echo "== Put object"

if [ -z "$1" ]; then
    echo "Bucket name needed to put object to"
    exit 1
fi

if [ -z "$2" ]; then 
    echo "Filename needed to upload to bucket"
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2
OBJECT_KEY=$(basename "$FILE_NAME")


aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILE_NAME \
--key "files/$OBJECT_KEY"